### ISSUE TITLE
Getting NULL pointer error while import 

### ISSUE THREAD

**Issue by vivekvpandya** [Enide/Eclipse-bootstrap-e4#1]
Getting NULL pointer error while i
![null pointer](https://cloud.githubusercontent.com/assets/5086212/8643768/d9c3add6-2955-11e5-9f76-bd7539ce21cb.PNG)
mport

**Comment by paulvi** [comment]
What plugins were selected?

Have you checked that you can open repositories listed inside, like
https://github.com/Enide/Eclipse-bootstrap-e4/blob/master/Eclipse-bootstrap-e4.p2f#L58

**Comment by vivekvpandya** [comment]
Sorry , perhaps due to proxy or Firewall my eclipse is not able to access the mentioned repository.

**Comment by vivekvpandya** [comment]
Closing the issue , but I would request you to add some sensible error message so that user can understand what is wrong .

**Comment by paulvi** [comment]
This is Eclipse feature, this repo just holds .p2f file
